name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t python-grpcio .

      - name: Get grpc version
        run: |
          echo "GRPC_VERSION=$(docker run -v "$(pwd)/tests/test.py":/app/test.py python-grpcio venv/bin/python test.py)" >> "$GITHUB_ENV"
          echo "EXPECTED_VERSION=$(grep grpcio < requirements.txt | grep -oP '.*\b\K\d+\.\d+\.\d+\b')" >> "$GITHUB_ENV"

      - name: Check grpc version
        run: |
          echo "detected version: ${GRPC_VERSION}"
          echo "expected version: ${EXPECTED_VERSION}"

      - name: Assert version
        if: env.GRPC_VERSION != env.EXPECTED_VERSION
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('version check failed')
