name: Docker Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t python-grpcio .

      - name: Get grpc version
        run: |
          echo "GRPC_VERSION=$(docker run -v "$(pwd)/tests/test.py":/test.py python-grpcio python test.py)" >> $GITHUB_ENV
          echo "EXPECTED_VERSION=$(cat requirements.txt | grep grpcio | grep -oP '.*\b\K\d+\.\d+\.\d+\b')" >> $GITHUB_ENV

      - name: Check grpc version
        run: |
          echo "detected version: ${GRPC_VERSION}"
          echo "expected version: ${EXPECTED_VERSION}"

      - name: Assert version
        if: env.GRPC_VERSION != env.EXPECTED_VERSION
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('version check failed')
