name: Build and Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Build Docker image
        run: docker build -t python-grpcio .

      - name: Get grpc version
        run: |
          echo "GRPC_VERSION=$(docker run -v "$(pwd)/tests/test.py":/app/test.py python-grpcio venv/bin/python test.py)" >> "$GITHUB_ENV"
          echo "EXPECTED_VERSION=$(grep grpcio < requirements.txt | grep -oP '.*\b\K\d+\.\d+\.\d+\b')" >> "$GITHUB_ENV"

      - name: Check grpc version
        run: |
          echo "detected version: ${GRPC_VERSION}"
          echo "expected version: ${EXPECTED_VERSION}"

      - name: Assert version
        if: env.GRPC_VERSION != env.EXPECTED_VERSION
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            core.setFailed('version check failed')
